name: Integration tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: OTP ${{ matrix.otp_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: erlang:${{matrix.otp_version}}

    strategy:
      matrix:
        otp_version: ['28', '27', '25', '23']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: rebar3 compile
    - name: Dialyzer
      run: rebar3 as test dialyzer
    - name: EUnit
      run: TERM=xterm rebar3 eunit
