name: OTP bump

on:
  push:
    branches:
      - '*'

jobs:
  otp-bump:
    name: Bump OTP versions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Setup dependencies
      run: pip install requests beautifulsoup4
    - name: Pull OTP versions from Debian
      run: touch touche; echo Chui > touche #python3 otp-bump.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        delete-branch: true
        commit-message: 'Bump OTP'
        branch: 'create-pull-request/otp-bump'
        title: 'OTP bump'
        body: |
          OTP bump
